name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  camera: ^0.11.0+2
  convex_bottom_bar: ^3.2.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3

  geocoding: ^3.0.0
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  http: ^1.2.2
  intl : 
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Bold.ttf
        - asset: assets/fonts/Inter_18pt-ExtraBold.ttf
        - asset: assets/fonts/Inter_18pt-ExtraLight.ttf
        - asset: assets/fonts/Inter_18pt-Light.ttf
        - asset: assets/fonts/Inter_18pt-Medium.ttf
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
        - asset: assets/fonts/Inter_18pt-Thin.ttf

